name: Deploy to Vercel

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual trigger from GitHub Actions tab

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Trigger Vercel Deployment (Main)
        run: curl -X POST ${{ secrets.VERCEL_DEPLOY_HOOK }}

      - name: Trigger Vercel Deployment (Dev)
        run: curl -X POST ${{ secrets.VERCEL_DEPLOY_HOOK_DEV }}
